AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    Cors:
      AllowMethods: '''OPTIONS,POST,GET'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
  Function:
    Environment:
      Variables:
        REGION: us-west-2
Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      CodeUri: s3://aws-serverless-lambda-dynamodb/43797434dcb2a15d3d51a9a7cb6ab072
  GetPlace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-place.handler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /place/{id}
            Method: get
      CodeUri: s3://aws-serverless-lambda-dynamodb/43797434dcb2a15d3d51a9a7cb6ab072
  CreatePlace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-place.handler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /create
            Method: post
      CodeUri: s3://aws-serverless-lambda-dynamodb/43797434dcb2a15d3d51a9a7cb6ab072
  UpdatePlace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update-place.handler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /update
            Method: post
      CodeUri: s3://aws-serverless-lambda-dynamodb/43797434dcb2a15d3d51a9a7cb6ab072
  DeletePlace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete-place.handler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /delete
            Method: post
      CodeUri: s3://aws-serverless-lambda-dynamodb/43797434dcb2a15d3d51a9a7cb6ab072
  GetUploadLocation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-upload-location.handler
      Runtime: nodejs10.x
      Policies: AmazonS3FullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /get-upload-location
            Method: post
      CodeUri: s3://aws-serverless-lambda-dynamodb/43797434dcb2a15d3d51a9a7cb6ab072
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: 2012-10-17
  PlacesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Places
      AttributeDefinitions:
      - AttributeName: placeKey
        AttributeType: S
      KeySchema:
      - AttributeName: placeKey
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1
