AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Environment:
      Variables:
        AWS_DYNAMODB_ENDPOINT: http://docker.for.mac.host.internal:8000
        AWS_REGION: 'us-west-2'
Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
  GetPerson:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getPerson
      Runtime: nodejs10.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /person/{id}
            Method: get
  AddPerson:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.addPerson
      Runtime: nodejs10.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /add
            Method: post
  UpdatePerson:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.updatePerson
      Runtime: nodejs10.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /update
            Method: post
  DeletePerson:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.deletePerson
      Events:
      Runtime: nodejs10.x
        GetEvent:
          Type: Api
          Properties:
            Path: /delete
            Method: post
  PersonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Persons"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      KeySchema:
        - AttributeName: "personKey"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "personKey"
          AttributeType: "S"